### ISSUE TITLE
Adding custom widgets

### ISSUE THREAD

**Issue by excitedbox** [CURTLab/LVGLBuilder#1]
Looking at the core it looks like you are using hard coded lists for the available widgets, symbols, etc. but wouldn´t it be better to populate those lists with a loop from the widget directory for example so that people can add their own widgets later without having to touch the code. The Littlevgl library supports adding widgets so I think it would be good to add that now to save on work later on.

Also I was wondering what was missing to make the canvas widget work? That is the only thing missing until I can use the builder for my project. Not many comments in the code and I would have to do a deeper dive to get a grasp on it.

**Comment by CURTLab** [comment]
Sorry for the late answer. The project grew very fast and I developed it to fit my needs. 

I was thinking about configuration files for widget description (since most of the properties are abstracted) too but at first I wanted no additional files besiedes the executable. 

I'm willing to extend the project for custom widgets (using json descriptors) but what do you think is better. Using one file for each widget or combine them into one?

**Comment by excitedbox** [comment]
Hi,
Thanks for your answer. I think it would be best to make it 1 file for each widget. 

I have been spending weeks looking into Embedded Gui libraries and there are really very few good choices and none that are free, easy to use AND offer a GUI Builder. That is why I think it is important for Littlevgl to have a GUI builder that is also expandable. Once there is solid base others will be able to create widgets and if they are in their own file it will be easy to just add them to a plugin directory.

I think with a little work this project could really take off and actually provide a critical piece to the maker ecosystem that is currently missing. Right now people building their own projects are very limited on UI options which leaves maker projects largely unusable outside of the maker space. The big promise of Arduino and these maker boards was that it would allow anyone to develop a product but without a good user interface that can never be achieved. We don´t need another weather station etc. but without a good GUI interface that is all we will get. The explosive adoption of the personal PC has been attributed to the birth of GUI operating systems and I believe the same will happen once LittleVGL gets a proper GUI Builder.

I would be happy to help achieve this goal in any way I can though my background is mostly in web development so making a GUI Builder is beyond my skills. Maybe I can help make a website and develop a monetization strategy through the sale of compatible displays and LCD BEZELS which are another crucial piece that is missing right now for anyone without a 3D printer.
