### ISSUE TITLE
arm64 linux not support

### ISSUE THREAD

**Issue by ddkwork** [CURTLab/LVGLBuilder#14]
arm64 linux seem not supposed, the widget not view. And the tree widget not has, can you add it? Thank you.

![Screenshot_20210622_080441_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/122843020-0e32ca80-d331-11eb-9b87-384b40e437ff.jpg)

**Comment by mrQzs** [comment]
@DiskGetor  You need to switch to the dev-v7 branch, because the lvgl of the master branch is lvgl6.0, and some functions are not implemented.

**Comment by mrQzs** [comment]
![image](https://user-images.githubusercontent.com/37052865/122875363-bdd65f80-d366-11eb-83ac-611ba831e662.png)
![image](https://user-images.githubusercontent.com/37052865/122875426-d0e92f80-d366-11eb-8648-ba3ad1b6b1b2.png)
@DiskGetor

**Comment by mrQzs** [comment]
@DiskGetor If you are developing a program based on lvgl6.0, you can only create a new page.  Because some problems in the multi-page situation have not been corrected on the master branch.

**Comment by ddkwork** [comment]
> @DiskGetor If you are developing a program based on lvgl6.0, you can only create a new page. Because some problems in the multi-page situation have not been corrected on the master branch.

I'm  sorry, I can't  build v7
![Screenshot_20210622_220933_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/122940084-bcc52280-d3a6-11eb-8134-3f19bcec45cb.jpg)

**Comment by mrQzs** [comment]
What is your qt version? You may need to git clean, then recompile.

**Comment by mrQzs** [comment]
@DiskGetor What is your qt version? You may need to git clean, then recompile.

**Comment by ddkwork** [comment]
> @DiskGetor 什么是您的夸脱的版本吗？ 你可能需要一件干净，然后重新编译。

5.12

**Comment by mrQzs** [comment]
![image](https://user-images.githubusercontent.com/37052865/123101812-ff4e3400-d466-11eb-9fa9-65021e4627cd.png)
@DiskGetor 
我用qt12.1测了一下,发现没问题,就是newdialog要加上cmath的头文件,没有出现你这种一大堆的错误...

**Comment by mrQzs** [comment]
@DiskGetor 你要不明天早上拉取一下最新的代码,我等会加上cmathi头文件,然后你编译看看.因为我用linux编译过好几次release版本了,都没出现你这个情况...

**Comment by mrQzs** [comment]
我已经提交好代码了,你拉取测试一下.最好重新建一个文件夹吧.还有你是什么linux版本的系统? centos?

**Comment by ddkwork** [comment]
> 我已经提交好代码了,你拉取测试一下.最好重新建一个文件夹吧.还有你是什么linux版本的系统? centos?

大湿，还是有好几个错误，不如加您QQ连接我这边的vnc吧，我的2762713521

**Comment by ddkwork** [comment]
> 我已经提交好代码了,你拉取测试一下.最好重新建一个文件夹吧.还有你是什么linux版本的系统? centos?

manjaro,在termux下装的

**Comment by mrQzs** [comment]
@DiskGetor   我晚上装个manjaro看下吧,急需的话,ubuntu是没问题的.

**Comment by mrQzs** [comment]
![image](https://user-images.githubusercontent.com/37052865/123330432-9652e300-d570-11eb-9e69-28da4e8c4ba9.png)

@DiskGetor manjaro20 可以编译通过. 我的qt是官方镜像下载安装的,然后就用了pacman -S core/gcc 和pacman -S make 没了

**Comment by ddkwork** [comment]
> ![image](https://user-images.githubusercontent.com/37052865/123330432-9652e300-d570-11eb-9e69-28da4e8c4ba9.png)
> 
> @DiskGetor manjaro20 可以编译通过. 我的qt是官方镜像下载安装的,然后就用了pacman -S core/gcc 和pacman -S make 没了

是啊，最近尝试好几个软件编译，ghidra mitmproxy qt6 base tools, amd64 linux都得行，aarch64总是出错，您装的这个应该是amd64，试试aarch64吧，

**Comment by mrQzs** [comment]
@DiskGetor  你是用arm版本的编译器编译qt源码生成qt的吧？你看那些的错误，错误都错在官方头文件上。。。你是不是编译少了一些组件。。。代码本身跨平台也应该支持，因为需要特定架构的内容都没有。
