### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by EmbolismSoil** [CURTLab/LVGLBuilder#16]
Qt version: 5.9.9
OS: ubuntu 18.04

LVGLProject.cpp: In static member function ‘static LVGLProject* LVGLProject::load(const QString&)’:
LVGLProject.cpp:49:27: error: no match for ‘operator[]’ (operand types are ‘QJsonDocument’ and ‘const char [5]’)
  QJsonObject lvglObj = doc["lvgl"].toObject();
                           ^
LVGLProject.cpp:61:27: error: no match for ‘operator[]’ (operand types are ‘QJsonDocument’ and ‘const char [7]’)
  QJsonArray imageArr = doc["images"].toArray();
                           ^
LVGLProject.cpp:72:26: error: no match for ‘operator[]’ (operand types are ‘QJsonDocument’ and ‘const char [6]’)
  QJsonArray fontArr = doc["fonts"].toArray();
                          ^

**Comment by mrQzs** [comment]
估计是我最后改动的代码导致在Ubuntu上编译不过吧，最近抽个时间完善一下。

**Comment by diver197** [comment]
G:\LVGLBuilder\LVGLFontDialog.h:28: error: field 'm_index' has incomplete type 'QHash<QString, int>'
In file included from ..\LVGLBuilder\LVGLFontDialog.cpp:1:
..\LVGLBuilder\LVGLFontDialog.h:28:22: error: field 'm_index' has incomplete type 'QHash<QString, int>'
  QHash<QString, int> m_index;
G:\LVGLBuilder\LVGLWidgetListView.cpp:27: error: incomplete type 'QIODevice' used in nested name specifier
..\LVGLBuilder\LVGLWidgetListView.cpp: In member function 'virtual void LVGLWidgetListView::startDrag(Qt::DropActions)':
..\LVGLBuilder\LVGLWidgetListView.cpp:27:42: error: incomplete type 'QIODevice' used in nested name specifier
  QDataStream stream(&encoded, QIODevice::ReadOnly);
G:\LVGLBuilder\properties\LVGLPropertySeries.cpp:239: error: no matching function for call to 'max(int&, qsizetype)'
..\LVGLBuilder\properties\LVGLPropertySeries.cpp: In member function 'virtual void LVGLPropertySeries::updateWidget(LVGLObject*)':
..\LVGLBuilder\properties\LVGLPropertySeries.cpp:239:50: error: no matching function for call to 'max(int&, qsizetype)'
   maxPoints = std::max(maxPoints, s.points.size());
G:\LVGLBuilder\properties\LVGLPropertySeries.cpp:332: error: no matching function for call to 'max(int&, qsizetype)'
..\LVGLBuilder\properties\LVGLPropertySeries.cpp:332:54: error: no matching function for call to 'max(int&, qsizetype)'
    maxPoints = std::max(maxPoints, item.points.size());

win10
Qt Creator 4.15.1
Based on Qt 5.15.2 (MSVC 2019, 64 bit)

**Comment by mrQzs** [comment]
@diver197 我两台电脑，除了不是msvc2019的，都可以编译通过，这个错误看起来更像是缺少头文件。。。

**Comment by diver197** [comment]
我的两台电脑编译都出现相同的问题，是需要特殊设置吗？

**Comment by diver197** [comment]
您是在Linux下编译的？

**Comment by mrQzs** [comment]
@diver197 你看下是不是 dev-v7分支，然后回退到v1.0.3的发布release的那条记录。 因为发布1.0.3的版本，全平台都编译通过了。

**Comment by sangko-dgq** [comment]
'QHash<QString, int>'
