### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by sangko-dgq** [CURTLab/LVGLBuilder#18]
![image](https://user-images.githubusercontent.com/73400366/131186588-dcd4f958-f050-4388-b8a0-70a45356664f.png)

**Comment by sangko-dgq** [comment]
![image](https://user-images.githubusercontent.com/73400366/131186588-dcd4f958-f050-4388-b8a0-70a45356664f.png)
C:\Users\Administrator\Desktop\LVGLBuilder\LVGLFontDialog.h:28: error: field 'm_index' has incomplete type 'QHash<QString, int>'
In file included from ../LVGLBuilder/LVGLFontDialog.cpp:1:
../LVGLBuilder/LVGLFontDialog.h:28:22: error: field 'm_index' has incomplete type 'QHash<QString, int>'
  QHash<QString, int> m_index;
                      ^~~~~~~

**Comment by hiperiondev** [comment]
A lot of error here (Fedora 34):

core/LVGLNewDialog.cpp: En el constructor ‘LVGLNewDialog::LVGLNewDialog(QWidget*)’:
core/LVGLNewDialog.cpp:56:3: error: ‘QFile’ no se declaró en este ámbito
   56 |   QFile file(":/qss/normal/LVGLNewDialog.qss");
      |   ^~~~~
core/LVGLNewDialog.cpp:57:3: error: ‘file’ no se declaró en este ámbito
   57 |   file.open(QFile::ReadOnly);
      |   ^~~~
core/LVGLNewDialog.cpp:57:13: error: ‘QFile’ no es una clase, un espacio de nombres o una enumeración
   57 |   file.open(QFile::ReadOnly);
      |             ^~~~~
core/LVGLNewDialog.cpp: En la función miembro ‘virtual void LVGLNewDialog::mousePressEvent(QMouseEvent*)’:
core/LVGLNewDialog.cpp:108:8: error: uso no válido del tipo incompleto ‘class QMouseEvent’
  108 |   if (e->button() & Qt::LeftButton) {
      |        ^~
En el fichero incluido desde /usr/include/qt5/QtWidgets/qdialog.h:44,
                 desde /usr/include/qt5/QtWidgets/QDialog:1,
                 desde core/LVGLNewDialog.h:4,
                 desde core/LVGLNewDialog.cpp:1:
/usr/include/qt5/QtWidgets/qwidget.h:72:7: nota: forward declaration of ‘class QMouseEvent’
   72 | class QMouseEvent;
      |       ^~~~~~~~~~~
core/LVGLNewDialog.cpp:109:17: error: uso no válido del tipo incompleto ‘class QMouseEvent’
  109 |     m_curPos = e->globalPos() - frameGeometry().topLeft();
      |                 ^~
En el fichero incluido desde /usr/include/qt5/QtWidgets/qdialog.h:44,
                 desde /usr/include/qt5/QtWidgets/QDialog:1,
                 desde core/LVGLNewDialog.h:4,
                 desde core/LVGLNewDialog.cpp:1:
/usr/include/qt5/QtWidgets/qwidget.h:72:7: nota: forward declaration of ‘class QMouseEvent’
   72 | class QMouseEvent;
      |       ^~~~~~~~~~~
core/LVGLNewDialog.cpp: En la función miembro ‘virtual void LVGLNewDialog::mouseMoveEvent(QMouseEvent*)’:
core/LVGLNewDialog.cpp:117:8: error: uso no válido del tipo incompleto ‘class QMouseEvent’
  117 |   if (e->buttons() & Qt::LeftButton && m_clicked)
      |        ^~
En el fichero incluido desde /usr/include/qt5/QtWidgets/qdialog.h:44,
                 desde /usr/include/qt5/QtWidgets/QDialog:1,
                 desde core/LVGLNewDialog.h:4,
                 desde core/LVGLNewDialog.cpp:1:
/usr/include/qt5/QtWidgets/qwidget.h:72:7: nota: forward declaration of ‘class QMouseEvent’
   72 | class QMouseEvent;
      |       ^~~~~~~~~~~
core/LVGLNewDialog.cpp:118:11: error: uso no válido del tipo incompleto ‘class QMouseEvent’
  118 |     move(e->globalPos() - m_curPos);
      |           ^~
En el fichero incluido desde /usr/include/qt5/QtWidgets/qdialog.h:44,
                 desde /usr/include/qt5/QtWidgets/QDialog:1,
                 desde core/LVGLNewDialog.h:4,
                 desde core/LVGLNewDialog.cpp:1:
/usr/include/qt5/QtWidgets/qwidget.h:72:7: nota: forward declaration of ‘class QMouseEvent’
   72 | class QMouseEvent;
      |       ^~~~~~~~~~~
core/LVGLNewDialog.cpp: En la función miembro ‘virtual void LVGLNewDialog::mouseReleaseEvent(QMouseEvent*)’:
core/LVGLNewDialog.cpp:123:52: aviso: parámetro ‘e’ sin uso [-Wunused-parameter]
  123 | void LVGLNewDialog::mouseReleaseEvent(QMouseEvent *e) { m_clicked = false; }
      |                                       ~~~~~~~~~~~~~^
core/LVGLNewDialog.cpp: En la función miembro ‘virtual void LVGLNewDialog::keyPressEvent(QKeyEvent*)’:
core/LVGLNewDialog.cpp:126:8: error: uso no válido del tipo incompleto ‘class QKeyEvent’
  126 |   if (e->key() == Qt::Key_Enter || e->key() == Qt::Key_Return) accept();
      |        ^~
En el fichero incluido desde /usr/include/qt5/QtWidgets/qdialog.h:44,
                 desde /usr/include/qt5/QtWidgets/QDialog:1,
                 desde core/LVGLNewDialog.h:4,
                 desde core/LVGLNewDialog.cpp:1:
/usr/include/qt5/QtWidgets/qwidget.h:75:7: nota: forward declaration of ‘class QKeyEvent’
   75 | class QKeyEvent;
      |       ^~~~~~~~~
core/LVGLNewDialog.cpp:126:37: error: uso no válido del tipo incompleto ‘class QKeyEvent’
  126 |   if (e->key() == Qt::Key_Enter || e->key() == Qt::Key_Return) accept();
      |                                     ^~
En el fichero incluido desde /usr/include/qt5/QtWidgets/qdialog.h:44,
                 desde /usr/include/qt5/QtWidgets/QDialog:1,
                 desde core/LVGLNewDialog.h:4,
                 desde core/LVGLNewDialog.cpp:1:
/usr/include/qt5/QtWidgets/qwidget.h:75:7: nota: forward declaration of ‘class QKeyEvent’
   75 | class QKeyEvent;
      |       ^~~~~~~~~
core/LVGLNewDialog.cpp: En la función miembro ‘virtual void LVGLNewDialog::paintEvent(QPaintEvent*)’:
core/LVGLNewDialog.cpp:131:45: aviso: parámetro ‘event’ sin uso [-Wunused-parameter]
  131 | void LVGLNewDialog::paintEvent(QPaintEvent *event) {
      |                                ~~~~~~~~~~~~~^~~~~
make: *** [Makefile:17017: build/x64/obj/release/LVGLNewDialog.o] Error 1
