### ISSUE TITLE
Building with Qt Creator fails

### ISSUE THREAD

**Issue by McMornan** [CURTLab/LVGLBuilder#9]
Hi,

I followed your instructions and downloaded the Qt framework. However when I try to build the project building fails with an error:

C:\Users\deuts\Desktop\LVGLBuilder-master\properties\LVGLPropertyVal2.cpp:51: Fehler: invalid use of non-static data member 'LVGLProperty::m_parent'
..\LVGLBuilder-master\properties\LVGLPropertyVal2.cpp:49:6:   required from here
..\LVGLBuilder-master\properties\LVGLPropertyVal2.cpp:51:67: error: invalid use of non-static data member 'LVGLProperty::m_parent'
  LVGLPropertyVal2<T> *d = reinterpret_cast<LVGLPropertyVal2<T> *>(m_parent);
                                                                   ^~~~~~~~

this is the code:

template<class T>
void LVGLPropertyVal2<T>::LVGLPropertyVal::set(LVGLObject *obj, T value)
{
	LVGLPropertyVal2<T> *d = reinterpret_cast<LVGLPropertyVal2<T> *>(m_parent);
	if (m_idx == 0)
		d->m_setter(obj->obj(), value, d->m_item2->get(obj));
	else if (m_idx == 1)
		d->m_setter(obj->obj(), d->m_item1->get(obj), value);
}

**Comment by CURTLab** [comment]
What's your compiler and Qt version?

**Comment by McMornan** [comment]
QT Creator 4.12.4 (downloaded today) and MSVC:
Microsoft Visual Studio Community 2019
Version 16.7.7
VisualStudio.16.Release/16.7.7+30621.155
Microsoft .NET Framework
Version 4.8.03752

Installierte Version: Community

Visual C++ 2019   00435-60000-00000-AA286
Microsoft Visual C++ 2019

Allgemeine Azure-Tools   1.10
Bietet allgemeine Dienste für die Verwendung durch Azure Mobile Services und Microsoft Azure-Tools.

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

Azure App Service-Tools v3.0.0   16.7.532.28833
Azure App Service-Tools v3.0.0

C#-Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
C#-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Cookiecutter   16.7.20248.6
Stellt Tools zum Suchen, Instanziieren und Anpassen von Vorlagen im Cookiecutter-Format bereit.

IntelliCode-Erweiterung   1.0
Detaillierte Informationen zur IntelliCode Visual Studio-Erweiterung

Microsoft Azure-Tools   2.9
Microsoft Azure-Tools für Microsoft Visual Studio 2019 – v2.9.30701.1

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++-Assistenten   1.0
Microsoft Visual C++-Assistenten

Node.js-Tools   1.5.20701.1 Commit Hash:b0da3724234b78593207434292d9f891440edea1
Fügt Unterstützung für das Entwickeln und Debuggen von Node.js-Apps in Visual Studio hinzu

NuGet-Paket-Manager   5.7.0
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter https://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.7.20248.6
Stellt IntelliSense, Projekte, Vorlagen, Debuggen, interaktive Fenster und weitere Unterstützung für Python-Entwickler bereit.

Python – Conda-Unterstützung   16.7.20248.6
Conda-Unterstützung für Python-Projekte.

Python – Django-Unterstützung   16.7.20248.6
Stellt Vorlagen und Integration für das Django-Webframework bereit.

Python – IronPython-Unterstützung   16.7.20248.6
Stellt Vorlagen und Integration für IronPython-basierte Projekte bereit.

Python – Unterstützung für die Profilerstellung   16.7.20248.6
Profilerstellungsunterstützung für Python-Projekte.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Testadapter für Google Test   1.0
Ermöglicht die Verwendung von Visual Studio-Testtools mit Komponententests, die für Google Test geschrieben wurden. Die Nutzungsbedingungen und Drittanbieterhinweise stehen im Installationsverzeichnis der Erweiterung zur Verfügung.

TypeScript-Tools   16.0.20702.2001
TypeScript-Tools für Microsoft Visual Studio

VC-Paket für Microsoft Visual Studio   1.0
VC-Paket für Microsoft Visual Studio

Visual Basic-Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
Visual Basic-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual C++ für Linux-Entwicklung   1.0.9.30523
Visual C++ für Linux-Entwicklung

Visual C++ für plattformübergreifende Mobile-Entwicklung (Android)   16.0.30309.115
Visual C++ für plattformübergreifende Mobile-Entwicklung (Android)

Visual Studio-Tools für CMake   1.0
Visual Studio-Tools für CMake

Visual Studio Code-Debugadapter-Hostpaket   1.0
Interopebene zum Hosten der Visual Studio Code-Adapter in Visual Studio

**Comment by CURTLab** [comment]
Please check if it works with the new fix

With my setup it works fine:
MSVC 2019 (enterprise)
Qt 5.15.1

**Comment by McMornan** [comment]
These errors are gone – now I have a few new ones … 

 



 

Von: CURTLab <notifications@github.com> 
Gesendet: Sonntag, 8. November 2020 19:31
An: CURTLab/LVGLBuilder <LVGLBuilder@noreply.github.com>
Cc: McMornan <deutsch.lars@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [CURTLab/LVGLBuilder] Building with Qt Creator fails (#9)

 

Please check if it works with the new fix

With my setup it works fine:
MSVC 2019 (enterprise)
Qt 5.15.1

**Comment by CURTLab** [comment]
Which ones?

**Comment by McMornan** [comment]
Ok, you did not seem to get my attached picture. Can I send it via Email ? It was a long list of unresolved references …

 

Von: CURTLab <notifications@github.com> 
Gesendet: Montag, 9. November 2020 16:25
An: CURTLab/LVGLBuilder <LVGLBuilder@noreply.github.com>
Cc: McMornan <deutsch.lars@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [CURTLab/LVGLBuilder] Building with Qt Creator fails (#9)

 

Which ones?

**Comment by McMornan** [comment]
Here you are:

C:\Users\deuts\Desktop\build-LVGLBuilder-Desktop_Qt_5_15_0_MinGW_64_bit-Debug\..\LVGLBuilder-master\properties\LVGLPropertyVal2.cpp:23: Fehler: undefined reference to `LVGLPropertyValT<short>::LVGLPropertyValT(short, short, QString, QString, std::function<void (_lv_obj_t*, short)>, std::function<short (_lv_obj_t*)>, LVGLProperty*)'

C:\Users\deuts\Desktop\build-LVGLBuilder-Desktop_Qt_5_15_0_MinGW_64_bit-Debug\..\LVGLBuilder-master\properties\LVGLPropertyVal2.cpp:24: Fehler: undefined reference to `LVGLPropertyValT<short>::LVGLPropertyValT(short, short, QString, QString, std::function<void (_lv_obj_t*, short)>, std::function<short (_lv_obj_t*)>, LVGLProperty*)'

C:\Users\deuts\Desktop\build-LVGLBuilder-Desktop_Qt_5_15_0_MinGW_64_bit-Debug\build\obj\LVGLPropertyVal2.o:-1: In function `LVGLPropertyVal2<unsigned short>::LVGLPropertyVal2(unsigned short, unsigned short, QString, std::function<unsigned short (_lv_obj_t*)>, unsigned short, unsigned short, QString, std::function<unsigned short (_lv_obj_t*)>, QString, std::function<void (_lv_obj_t*, unsigned short, unsigned short)>, QString, LVGLProperty*)':

C:\Users\deuts\Desktop\build-LVGLBuilder-Desktop_Qt_5_15_0_MinGW_64_bit-Debug\..\LVGLBuilder-master\properties\LVGLPropertyVal2.cpp:23: Fehler: undefined reference to `LVGLPropertyValT<unsigned short>::LVGLPropertyValT(unsigned short, unsigned short, QString, QString, std::function<void (_lv_obj_t*, unsigned short)>, std::function<unsigned short (_lv_obj_t*)>, LVGLProperty*)'

C:\Users\deuts\Desktop\build-LVGLBuilder-Desktop_Qt_5_15_0_MinGW_64_bit-Debug\..\LVGLBuilder-master\properties\LVGLPropertyVal2.cpp:24: Fehler: undefined reference to `LVGLPropertyValT<unsigned short>::LVGLPropertyValT(unsigned short, unsigned short, QString, QString, std::function<void (_lv_obj_t*, unsigned short)>, std::function<unsigned short (_lv_obj_t*)>, LVGLProperty*)'

C:\Users\deuts\Desktop\LVGLBuilder-master\widgets\LVGLCalendar.cpp:-1: Fehler: undefined reference to `LVGLPropertyMonthNames::DEFAULT'

C:\Users\deuts\Desktop\LVGLBuilder-master\widgets\LVGLCalendar.cpp:-1: Fehler: undefined reference to `LVGLPropertyDayNames::DEFAULT'

**Comment by CURTLab** [comment]
Should be fixed with the latest commit. Could you check it for me?

**Comment by McMornan** [comment]
Yes, will do with the next gui ... I went down the long and hard road of manual gui building for my devices for now ...
